- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/odom"
  gz_topic_name: "model/robot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/lidar3d/rmagine/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_topic_name: "/model/robot/lidar3d/rmagine/points"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/lidar3d/gazebo/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_topic_name: "/model/robot/lidar3d/gazebo/points"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_topic_name: "/model/robot/joint_states"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/TwistStamped"
  gz_topic_name: "/model/robot/cmd_vel"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# GT Poses
- ros_topic_name: "/tf_gt"
  gz_topic_name: "model/robot/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# DiffDrive Odom TF
- ros_topic_name: "/tf_odom"
  gz_topic_name: "model/robot/tf_odom"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS